### ISSUE TITLE
预训练权重怎么下载呢？

### ISSUE THREAD

**Issue by xl-alt** [RuipingL/TransKD#8]
readme里面的预训练权重下载链接已经失效，请问是否能加上新的预训练权重

**Comment by RuipingL** [comment]
It's derived from the SegFormer official repo. 
https://connecthkuhk-my.sharepoint.com/:f:/g/personal/xieenze_connect_hku_hk/EvOn3l1WyM5JpnMQFSEO5b8B7vrHw9kDaJGII-3N9KNhrg?e=cpydzZ
